import type { Post } from '@/types/post';

/**
 * Demo/seed data for the ZekkTech blog.
 * Used when Supabase is not configured yet.
 */
export const seedPosts: Post[] = [
  // === Pilihan Editor (Featured) ===
  {
    id: '1',
    title: 'Javascript Tingkat Lanjut',
    slug: 'javascript-tingkat-lanjut',
    content: 'Pelajari konsep-konsep tingkat lanjut dalam Javascript seperti closure, prototype chain, event loop, dan masih banyak lagi. Artikel ini akan membahas secara mendalam tentang bagaimana Javascript bekerja di balik layar dan bagaimana memanfaatkan fitur-fitur canggih untuk menulis kode yang lebih baik.',
    excerpt: 'Pelajari konsep-konsep tingkat lanjut dalam Javascript seperti closure, prototype chain, dan event loop.',
    cover_url: null,
    category: 'Pilihan Editor',
    author_name: 'Kadek Surya',
    reading_time: 5,
    featured: true,
    published: true,
    created_at: '2025-02-12T08:00:00Z',
    updated_at: '2025-02-12T08:00:00Z',
  },
  {
    id: '2',
    title: 'Mengenal CSS Grid',
    slug: 'mengenal-css-grid',
    content: 'CSS Grid adalah sistem layout dua dimensi yang powerful untuk membangun layout web modern. Dengan CSS Grid, kamu bisa membuat layout kompleks dengan kode yang lebih bersih dan lebih mudah dipahami.',
    excerpt: 'CSS Grid adalah sistem layout dua dimensi yang powerful untuk membangun layout web modern.',
    cover_url: null,
    category: 'Pilihan Editor',
    author_name: 'Kadek Surya',
    reading_time: 5,
    featured: true,
    published: true,
    created_at: '2025-02-12T08:00:00Z',
    updated_at: '2025-02-12T08:00:00Z',
  },
  {
    id: '3',
    title: 'Animasi CSS Untuk Pemula',
    slug: 'animasi-css-untuk-pemula',
    content: 'Belajar membuat animasi yang menarik menggunakan CSS. Dari transisi sederhana hingga keyframe animations yang kompleks, pelajari cara membuat website kamu lebih hidup dan interaktif.',
    excerpt: 'Belajar membuat animasi yang menarik menggunakan CSS transitions dan keyframes.',
    cover_url: null,
    category: 'Pilihan Editor',
    author_name: 'Kadek Surya',
    reading_time: 8,
    featured: true,
    published: true,
    created_at: '2025-02-12T08:00:00Z',
    updated_at: '2025-02-12T08:00:00Z',
  },
  {
    id: '4',
    title: 'React JS Untuk Pemula',
    slug: 'react-js-untuk-pemula',
    content: 'Panduan lengkap untuk memulai belajar React JS dari nol. Pelajari dasar-dasar React seperti components, props, state, dan hooks. Cocok untuk yang baru memulai perjalanan frontend development.',
    excerpt: 'Panduan lengkap untuk memulai belajar React JS dari nol.',
    cover_url: null,
    category: 'Pilihan Editor',
    author_name: 'Kadek Surya',
    reading_time: 5,
    featured: true,
    published: true,
    created_at: '2025-02-12T08:00:00Z',
    updated_at: '2025-02-12T08:00:00Z',
  },

  // === CSS Dasar ===
  {
    id: '5',
    title: 'CSS Flexbox Lengkap',
    slug: 'css-flexbox-lengkap',
    content: 'Panduan lengkap tentang CSS Flexbox. Pelajari cara menggunakan flex container, flex items, dan semua properti yang terkait untuk membuat layout yang responsif dan fleksibel.',
    excerpt: 'Panduan lengkap tentang CSS Flexbox untuk layout yang responsif.',
    cover_url: null,
    category: 'CSS Dasar',
    author_name: 'Kadek Surya',
    reading_time: 5,
    featured: false,
    published: true,
    created_at: '2025-02-12T08:00:00Z',
    updated_at: '2025-02-12T08:00:00Z',
  },
  {
    id: '6',
    title: 'Mengenal CSS Grid',
    slug: 'mengenal-css-grid-dasar',
    content: 'Pelajari dasar-dasar CSS Grid layout untuk membuat tata letak web yang modern dan responsif. Dari grid container hingga grid items, semua dibahas lengkap di sini.',
    excerpt: 'Pelajari dasar-dasar CSS Grid layout untuk tata letak web modern.',
    cover_url: null,
    category: 'CSS Dasar',
    author_name: 'Kadek Surya',
    reading_time: 5,
    featured: false,
    published: true,
    created_at: '2025-02-12T08:00:00Z',
    updated_at: '2025-02-12T08:00:00Z',
  },
  {
    id: '7',
    title: 'Cara Membuat Div Tengah',
    slug: 'cara-membuat-div-tengah',
    content: 'Semua cara yang bisa kamu gunakan untuk membuat div berada di tengah halaman. Dari teknik klasik menggunakan margin auto hingga teknik modern menggunakan Flexbox dan Grid.',
    excerpt: 'Semua cara untuk membuat div berada di tengah halaman menggunakan CSS.',
    cover_url: null,
    category: 'CSS Dasar',
    author_name: 'Kadek Surya',
    reading_time: 5,
    featured: false,
    published: true,
    created_at: '2025-02-12T08:00:00Z',
    updated_at: '2025-02-12T08:00:00Z',
  },
  {
    id: '8',
    title: 'Animasi CSS Untuk Pemula',
    slug: 'animasi-css-pemula',
    content: 'Belajar membuat animasi sederhana dengan CSS. Pelajari transition, transform, dan keyframes untuk menghidupkan website kamu.',
    excerpt: 'Belajar membuat animasi sederhana dengan CSS transitions dan keyframes.',
    cover_url: null,
    category: 'CSS Dasar',
    author_name: 'Kadek Surya',
    reading_time: 5,
    featured: false,
    published: true,
    created_at: '2025-02-12T08:00:00Z',
    updated_at: '2025-02-12T08:00:00Z',
  },

  // === Javascript Tingkat Dasar ===
  {
    id: '9',
    title: 'Array Pada Javascript',
    slug: 'array-pada-javascript',
    content: 'Panduan lengkap tentang Array di Javascript. Pelajari cara membuat, memanipulasi, dan menggunakan method-method array seperti map, filter, reduce, dan masih banyak lagi.',
    excerpt: 'Panduan lengkap tentang Array dan method-methodnya di Javascript.',
    cover_url: null,
    category: 'Javascript Tingkat Dasar',
    author_name: 'Kadek Surya',
    reading_time: 5,
    featured: false,
    published: true,
    created_at: '2025-02-12T08:00:00Z',
    updated_at: '2025-02-12T08:00:00Z',
  },
  {
    id: '10',
    title: 'Javascript Tingkat Lanjut',
    slug: 'javascript-tingkat-lanjut-dasar',
    content: 'Mendalami konsep lanjutan Javascript termasuk async/await, promises, dan error handling yang baik untuk aplikasi yang lebih robust.',
    excerpt: 'Mendalami konsep lanjutan Javascript termasuk async/await dan promises.',
    cover_url: null,
    category: 'Javascript Tingkat Dasar',
    author_name: 'Kadek Surya',
    reading_time: 5,
    featured: false,
    published: true,
    created_at: '2025-02-12T08:00:00Z',
    updated_at: '2025-02-12T08:00:00Z',
  },
  {
    id: '11',
    title: '7 Proyek Javascript Untuk Portfolio',
    slug: '7-proyek-javascript-untuk-portfolio',
    content: 'Kumpulan proyek Javascript yang bagus untuk ditambahkan ke portfolio. Dari todo app hingga weather app, pelajari cara membuat proyek yang mengesankan.',
    excerpt: 'Kumpulan proyek Javascript yang bagus untuk portfolio developer.',
    cover_url: null,
    category: 'Javascript Tingkat Dasar',
    author_name: 'Kadek Surya',
    reading_time: 5,
    featured: false,
    published: true,
    created_at: '2025-02-12T08:00:00Z',
    updated_at: '2025-02-12T08:00:00Z',
  },
  {
    id: '12',
    title: 'Kalkulator Sederhana Dengan Javascript',
    slug: 'kalkulator-sederhana-dengan-javascript',
    content: 'Tutorial membuat kalkulator sederhana menggunakan HTML, CSS, dan Javascript. Proyek ini cocok untuk pemula yang ingin belajar DOM manipulation.',
    excerpt: 'Tutorial membuat kalkulator sederhana menggunakan HTML, CSS, dan Javascript.',
    cover_url: null,
    category: 'Javascript Tingkat Dasar',
    author_name: 'Kadek Surya',
    reading_time: 5,
    featured: false,
    published: true,
    created_at: '2025-02-12T08:00:00Z',
    updated_at: '2025-02-12T08:00:00Z',
  },

  // === React JS ===
  {
    id: '13',
    title: 'Belajar React JS Di Bulan Pertama',
    slug: 'belajar-react-js-di-bulan-pertama',
    content: 'Pengalaman dan tips belajar React JS di bulan pertama. Dari setup environment hingga membuat komponen pertama, pelajari langkah-langkah yang efektif.',
    excerpt: 'Pengalaman dan tips belajar React JS dari nol di bulan pertama.',
    cover_url: '/images/react-demo.svg',
    category: 'React JS',
    author_name: 'Kadek Surya',
    reading_time: 5,
    featured: false,
    published: true,
    created_at: '2025-02-12T08:00:00Z',
    updated_at: '2025-02-12T08:00:00Z',
  },
  {
    id: '14',
    title: 'Editor Markdown Dengan React JS',
    slug: 'editor-markdown-dengan-react-js',
    content: 'Tutorial membuat editor Markdown sederhana menggunakan React JS. Pelajari cara menggunakan state management dan third-party library untuk membuat fitur preview real-time.',
    excerpt: 'Tutorial membuat editor Markdown sederhana menggunakan React JS.',
    cover_url: '/images/react-demo.svg',
    category: 'React JS',
    author_name: 'Kadek Surya',
    reading_time: 5,
    featured: false,
    published: true,
    created_at: '2025-02-12T08:00:00Z',
    updated_at: '2025-02-12T08:00:00Z',
  },
  {
    id: '15',
    title: 'Mulai Belajar React JS',
    slug: 'mulai-belajar-react-js',
    content: 'Panduan memulai perjalanan React JS kamu. Pelajari fundamental yang penting seperti JSX, components, props, dan state yang menjadi dasar pengembangan React.',
    excerpt: 'Panduan memulai perjalanan React JS dari fundamental.',
    cover_url: '/images/react-demo.svg',
    category: 'React JS',
    author_name: 'Kadek Surya',
    reading_time: 5,
    featured: false,
    published: true,
    created_at: '2025-02-12T08:00:00Z',
    updated_at: '2025-02-12T08:00:00Z',
  },
  {
    id: '16',
    title: 'Membuat Game Tic Tac Toe Dengan React',
    slug: 'membuat-game-tic-tac-toe-dengan-react',
    content: 'Tutorial proyek membuat game Tic Tac Toe menggunakan React JS. Proyek klasik yang membantu memahami state management dan event handling di React.',
    excerpt: 'Tutorial membuat game Tic Tac Toe menggunakan React JS.',
    cover_url: '/images/react-demo.svg',
    category: 'React JS',
    author_name: 'Kadek Surya',
    reading_time: 5,
    featured: false,
    published: true,
    created_at: '2025-02-12T08:00:00Z',
    updated_at: '2025-02-12T08:00:00Z',
  },
];
